config/routes.rb
MprojDev1::Application.routes.draw do

  match "szukaj" => "home#search", :as => :search

  match "wiadomosci" => "front_infos#index", :as => :front_infos
  match "wiadomosc/:id" => "front_infos#show", :as => :front_info
  
  match "wydarzenia" => "front_events#index", :as => :front_events
  match "wydarzenie/:id" => "front_events#show", :as => :front_event
  
  match "o-projekcie" => "home#about", :as => :front_about

  match "video" => "front_videos#index", :as => :front_videos
  match "video/:id" => "front_videos#show", :as => :front_video

  match "galerie" => "front_galleries#index", :as => :front_galleries
  match "galeria/:id" => "front_galleries#show", :as => :front_gallery
  match "galeria-zwieksz-priorytet/:id" => "galleries#prior_up", :as => :pages_prior_up
  match "galeria-zmniejsz-priorytet/:id" => "galleries#prior_down", :as => :pages_prior_down

  match "kontakt" => "home#contact", :as => :contact

  match "english" => "home#english", :as => :english

  match "strony" => "front_pages#index", :as => :front_pages
  match "strona/:id" => "front_pages#show", :as => :front_page

  match "zapisz-do-neewslettera" => "home#subscribe", :as => :subscribe
  match "wyslij-wiadomosc" => "home#send_message", :as => :send_mesage

  resources :infos
  resources :events
  resources :galleries
  resources :vids
  resources :pages
  resources :newsletter_users

  match "admin" => "admin#index", :as => :admin
  match "admin/login" => "admin#login", :as => :admin_login
  match "admin/enter" => "admin#enter", :as => :admin_enter
  match "admin/logout" => "admin#logout", :as => :admin_logout

  root :to => 'home#index'

end

app/models/vid.rb
class Vid < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/vids_controller.rb
# -*- encoding: utf-8 -*-
class VidsController < AdminController

  def index
    @vids = Vid.all
  end

  def show
    @vid = Vid.find(params[:id])
  end

  def new
    @vid = Vid.new
  end

  def edit
    @vid = Vid.find(params[:id])
  end

  def create
    @vid = Vid.new(params[:vid])

      if @vid.save
        redirect_to vids_url, notice: 'News został dodany'
      else
        render action: "new"
      end
  end

  def update
    @vid = Vid.find(params[:id])

      if @vid.update_attributes(params[:vid])
        redirect_to vids_url, notice: "News został wyedytowany"
      else
        render action: "edit"
      end
  end

  def destroy
    @vid = Vid.find(params[:id])
    @vid.destroy

    redirect_to vids_url
  end
end

app/views/vids/_form.html.erb
<%= form_for(@vid, :html => {:multipart => true}) do |f| %>
  <% if @vid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vid.errors.count, "error") %> prohibited this vid from being saved:</h2>

      <ul>
      <% @vid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title, "Tytuł" %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :fileurl, "Wklej embed video" %>
    <%= f.text_area :fileurl %>
  </div>
  
  <div class="field">
    <%= f.label :description, "Opis" %>
    <%= f.text_area :description, :class => 'mceEditor' %>
  </div>
  
  <div class="actions">
    <%= f.submit "Zapisz" %>
  </div>
<% end %>

app/views/vids/edit.html.erb
<h1>Edytuj video</h1>

<%= render 'form' %>

<%= link_to 'Powrót', vids_path %>

app/views/vids/index.html.erb
<div>
  <h1>Video</h1>
  <%= link_to "Nowe video", new_vid_path %>
  <br/>
  <br/>
  <br/>
  
  <table width="100%">
    <tr>
      <th width="60%">Tytuł</th>
      <th width="20%">Data publikacji</th>
      <th width="20%">Akcje</th>
    </tr>
    
    <% @vids.each do |vid| %>
      <tr>
	<td><%= vid.title %></td>
	<td><%= vid.created_at.strftime("%d-%m-%Y %H:%M:%S") %></td>
	<td><%= link_to 'Edytuj', edit_vid_path(vid) %> | <%= link_to 'Usuń', vid, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/vids/new.html.erb
<h1>Dodaj nowe video</h1>

<%= render 'form' %>

<%= link_to 'Powrót', vids_path %>