config/routes.rb
MprojDev1::Application.routes.draw do

  match "szukaj" => "home#search", :as => :search

  match "wiadomosci" => "front_infos#index", :as => :front_infos
  match "wiadomosc/:id" => "front_infos#show", :as => :front_info
  
  match "wydarzenia" => "front_events#index", :as => :front_events
  match "wydarzenie/:id" => "front_events#show", :as => :front_event
  
  match "o-projekcie" => "home#about", :as => :front_about

  match "video" => "front_videos#index", :as => :front_videos
  match "video/:id" => "front_videos#show", :as => :front_video

  match "galerie" => "front_galleries#index", :as => :front_galleries
  match "galeria/:id" => "front_galleries#show", :as => :front_gallery
  match "galeria-zwieksz-priorytet/:id" => "galleries#prior_up", :as => :pages_prior_up
  match "galeria-zmniejsz-priorytet/:id" => "galleries#prior_down", :as => :pages_prior_down

  match "kontakt" => "home#contact", :as => :contact

  match "english" => "home#english", :as => :english

  match "strony" => "front_pages#index", :as => :front_pages
  match "strona/:id" => "front_pages#show", :as => :front_page

  match "zapisz-do-neewslettera" => "home#subscribe", :as => :subscribe
  match "wyslij-wiadomosc" => "home#send_message", :as => :send_mesage

  resources :infos
  resources :events
  resources :galleries
  resources :vids
  resources :pages
  resources :newsletter_users

  match "admin" => "admin#index", :as => :admin
  match "admin/login" => "admin#login", :as => :admin_login
  match "admin/enter" => "admin#enter", :as => :admin_enter
  match "admin/logout" => "admin#logout", :as => :admin_logout

  root :to => 'home#index'

end

app/controllers/home_controller.rb
# -*- encoding: utf-8 -*-
class HomeController < ApplicationController
  include ActionView::Helpers::TextHelper
  before_filter :init_right_panel

  def index
    @infos = Info.order("created_at DESC").limit(3)
  end


  def contact
    @page = Page.find_by_label('kontakt')
  end

  def english
    @page = Page.find_by_label('english')    
  end

  def about
    @page = Page.find_by_label('o-projekcie')
  end


  def subscribe
    if params[:email].present?
      @newsletter_user = NewsletterUser.new(:email => params[:email])
      
      if @newsletter_user.save
        redirect_to root_url, notice: "Pomyślnie zapisano do newslettera"
      else
        redirect_to root_url, alert: "E-mail ma niepoprawny format"
      end
    else
      redirect_to root_url, alert: "Aby zapisać się do newslettera musisz podac e-mail."
    end
  end


  def search
    if params[:key].present?
      params[:key] = truncate(params[:key].to_s, :length => 50)
      
      keys = params[:key].gsub(/[^0-9a-ząćęłńśóżź -]/i, '').split(/[\s\-]/).select{|k| k.size > 2}

      @result_infos = []
      @result_events = []
      @result_galleries = []
      @result_videos = []
      @result_pages = []

      keys.each do |key|
        prep_key = '%'+key+'%'
        @result_infos += Info.where("title LIKE ? OR content LIKE ?", prep_key, prep_key).to_a 
      end
      keys.each do |key|
        prep_key = '%'+key+'%'
        @result_events += Event.where("title LIKE ? OR content LIKE ?", prep_key, prep_key).to_a 
      end
      keys.each do |key|
        prep_key = '%'+key+'%'
        @result_galleries += Gallery.where("name LIKE ?", prep_key).to_a 
      end
      keys.each do |key|
        prep_key = '%'+key+'%'
        @result_videos += Vid.where("title LIKE ? OR description LIKE ?", prep_key, prep_key).to_a 
      end
      keys.each do |key|
        prep_key = '%'+key+'%'
        @result_pages += Page.where("title LIKE ? OR content LIKE ?", prep_key, prep_key).to_a 
      end
    end    
  end


  def send_message
    if params[:name].present? && params[:content].present? && params[:email].present? && params[:email] =~ /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
      ContactMailer.contact_email(params[:name], params[:email], params[:content]).deliver    
      redirect_to contact_url, notice: "Wiadomość wysłana"
    else
      redirect_to contact_url, alert: "Wypełnij prawidłowo pola formularza"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_metatags.html.erb
<title>
  Chronimy Wiśliska
</title>
<meta name="author" content="Towarzystwo na rzecz Ziemi">
<meta name="description" content="Strona internetowa projektu Towarzystwa na rzecz Ziemi pn. 'Rewitalizacja, ochrona
bioróżnorodności i wykorzystanie walorów starorzeczy Wisły, zatrzymanie degradacji doliny górnej Wisły jako korytarza
ekologicznego' w ramach Szwajcarsko-Polskiego Programu Współpracy.">
<meta name="keywords" content="starorzecza, wisła, dolina górnej wisły, wiśliska, korytarz ekologiczny, Natura 2000, ostoje sieci, ochrona przyrody, ochrona siedlisk, ochrona bioróżnorodności, bioróżnorodność, ochrona środowiska, Towarzystwo na rzecz Ziemi, wiślisko, starorzecze Wisły, fauna wiślisk, flora wiślisk, zwierzęta wiślisk, rośliny wiślisk, zwierzęta starorzeczy Wisły, roślinność starorzeczy Wisły, płazy w starorzeczach, żabie gody w starorzeczach, przyroda doliny Wisły, nadwiślański pejzaż, z biegiem Wisły, przyroda wiślisk, spływ Wisłą, szlaki turystyczne nad Wisłą, szlaki rowerowe nad Wisłą, wiślańskie szlaki turystyczne, wypoczynek nad Wisłą, urlop nad Wisłą, rekreacja nad Wisłą, tablice edukacyjne na starorzeczach, tablice edukacyjne nad Wisłą, tablice edukacyjne na wiśliskach, edukacja na starorzeczach, edukacja na wiśliskach, zarastanie starorzeczy, ochrona starorzeczy, ochrona wiślisk, waloryzacja starorzeczy, waloryzacja starorzeczy, ryby w starorzeczach, wędkowanie na starorzeczach, starorzecze laboratorium przyrody, kajaki na Wiśle, przewodnik po małopolskiej Wiśle, Vistula, krypa, spływ krypą, edukacyjne wycieczki krypą, krypa na Wiśle, małopolska Wisła, małopolskie wiśliska, małopolskie starorzecza Wisły, kalendarz nadwiślańskiej przyrody, nadwiślańska przyroda, ptasi szlak migracyjny na Wiśle, ochrona czynna starorzeczy, mała architektura nad starorzeczami, wiśliska źródłem bioróżnorodności, starorzecza a bioróżnorodność, przyrodnicze zasoby starorzeczy, powstawanie starorzeczy, narodziny starorzecza, śmierć starorzecza, rekultywacja starorzecza, Natura 2000 chroni starorzecza, zdjęcia starorzeczy, fotografowanie starorzeczy, wiśliska na zdjęciach, galeria wiślisk, galeria starorzeczy, fotogeniczne starorzecza, piękno starorzeczy, piękno wiślisk, ważki na starorzeczach, przyrodnicza wartość starorzeczy, mieszkańcy wiślisk, mieszkańcy starorzeczy, awifauna starorzeczy,
ptaki starorzeczy" />

app/views/home/about.html.erb
<% if @page.present? %>
  <h1 class="news">
    <i></i>
    <%= @page.title %>
  </h1>

  <div class="single-news">
    <%= raw @page.content %>
  </div>
<% end %>

app/views/home/contact.html.erb
<% if flash[:notice] %>
  <div class="response" id="mce-success-response"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="response" id="mce-error-response"><%= flash[:alert] %></div>
<% end %>


<% if @page.present? %>
  <h1 class="news">
    <i></i>
    <%= @page.title %>
  </h1>

  <div class="single-news">
    <%= raw @page.content %>
  </div>

  <p>
    Możesz również wykorzystać poniższy formularz.
  </p>
<% end %>


<div class="contact_form">
  <%= form_tag send_mesage_url do %>
    <label for="name">Twoje imię</label>
    <%= text_field_tag :name, '', :placeholder => "Imię" %>      
    <label for="email">Twój E-mail</label>
    <%= text_field_tag :email, '',:placeholder => "E-mail" %>      
    <label for="content">Wiadomość</label>
    <%= text_area_tag :content %>      
    <%= submit_tag "Wyślij" %>
  <% end %>
</div>

app/views/home/english.html.erb
<% if @page.present? %>
  <h1 class="news">
    <i></i>
    <%= @page.title %>
  </h1>

  <div class="single-news">
    <%= raw @page.content %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1 class="news">
  <i></i>
  Wiadomości
</h1>

<% @infos.each do |info| %>
  <div class="single-news">
    <h3>
      <%= link_to info.title, front_info_url(info) %>
    </h3>
    <div>
      <%= raw info.content %>
    </div>

    <div class="data">
      <span class="time">
        <i></i>
        <%= info.created_at.strftime("%d-%m-%Y %H:%M:%S") %>
      </span>
      <%#= link_to "Czytaj więcej...", front_info_url(info) %>
    </div>
  </div>
<% end %>

<div class="bottom-more">
  <%= link_to "Więcej...", front_infos_url %>
</div>

app/views/home/search.html.erb
<h1 class="news">
  <i></i>
  Wyniki wyszukiwania: <%= params[:key] %>
</h1>


<% if @result_infos.present? %>
  <br>
  <br>
  <h2>Wiadomości:</h2>
  <% @result_infos.each do |info| %>
    <div class="single-news">
      <h3>
        <%= link_to info.title, front_info_url(info) %>
      </h3>
      <div>
        <%= raw info.content %>
      </div>

      <div class="data">
        <span class="time">
          <i></i>
          <%= info.created_at.strftime("%d-%m-%Y %H:%M:%S") %>
        </span>
        <%= link_to "Czytaj więcej...", front_info_url(info) %>
      </div>
    </div>
  <% end %>
<% end %>

<% if @result_events.present? %>
  <br>
  <br>
  <h2>Wydarzenia:</h2>
  <% @result_events.each do |event| %>
    <div class="single-news">
      <h3>
        <%= link_to event.title, front_event_url(event) %>
      </h3>
      <div>
        <%= raw event.content %>
      </div>

      <div class="data">
        <span class="time">
          <i></i>
          <%= event.created_at.strftime("%d-%m-%Y %H:%M:%S") %>
        </span>
        <%= link_to "Czytaj więcej...", front_event_url(event) %>
      </div>
    </div>
  <% end %>
<% end %>

<% if @result_galleries.present? %>
  <br>
  <br>
  <h2>Galerie:</h2>
  <% @result_galleries.each_with_index do |gallery, index| %>
    <h2>
      <%= gallery.name %>
    </h2>

    <div class="gallery">
      <p>
        <% gallery.photos.each do |photo| %>
          <%= link_to( image_tag(photo.photo.small.url, :alt => photo.title, :title => photo.title), photo.photo.url, :class => 'fancybox', 'data-fancybox-group' => "gallery_#{index}", :title => "Autor zdjęcia: #{photo.description}" ) %>
        <% end %>
      </p>
    </div>
  <% end %>
<% end %>


<% if @result_videos.present? %>
  <br>
  <br>
  <h2>Video:</h2>
  <% @result_videos.each do |video| %>
    <h2>
      <%= video.title %>
    </h2>
    <p>
      <%= raw video.fileurl %>
    </p>
  <% end %>
<% end %>


<% if @result_pages.present? %>
  <br>
  <br>
  <h2>Strony:</h2>
  <% @result_pages.each do |page| %>
    <h2>
      <%= link_to page.title, front_page_url(page) %>
    </h2>  
  <% end %>
<% end %>