config/routes.rb
MprojDev1::Application.routes.draw do

  match "szukaj" => "home#search", :as => :search

  match "wiadomosci" => "front_infos#index", :as => :front_infos
  match "wiadomosc/:id" => "front_infos#show", :as => :front_info
  
  match "wydarzenia" => "front_events#index", :as => :front_events
  match "wydarzenie/:id" => "front_events#show", :as => :front_event
  
  match "o-projekcie" => "home#about", :as => :front_about

  match "video" => "front_videos#index", :as => :front_videos
  match "video/:id" => "front_videos#show", :as => :front_video

  match "galerie" => "front_galleries#index", :as => :front_galleries
  match "galeria/:id" => "front_galleries#show", :as => :front_gallery
  match "galeria-zwieksz-priorytet/:id" => "galleries#prior_up", :as => :pages_prior_up
  match "galeria-zmniejsz-priorytet/:id" => "galleries#prior_down", :as => :pages_prior_down

  match "kontakt" => "home#contact", :as => :contact

  match "english" => "home#english", :as => :english

  match "strony" => "front_pages#index", :as => :front_pages
  match "strona/:id" => "front_pages#show", :as => :front_page

  match "zapisz-do-neewslettera" => "home#subscribe", :as => :subscribe
  match "wyslij-wiadomosc" => "home#send_message", :as => :send_mesage

  resources :infos
  resources :events
  resources :galleries
  resources :vids
  resources :pages
  resources :newsletter_users

  match "admin" => "admin#index", :as => :admin
  match "admin/login" => "admin#login", :as => :admin_login
  match "admin/enter" => "admin#enter", :as => :admin_enter
  match "admin/logout" => "admin#logout", :as => :admin_logout

  root :to => 'home#index'

end

app/models/newsletter_user.rb
class NewsletterUser < ActiveRecord::Base

  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i

end

app/controllers/newsletter_users_controller.rb
# -*- encoding: utf-8 -*-
class NewsletterUsersController < AdminController

  def index
    @newsletter_users = NewsletterUser.all
  end

  def show
    @newsletter_user = NewsletterUser.find(params[:id])
  end

  def new
    @newsletter_user = NewsletterUser.new
  end

  def edit
    @newsletter_user = NewsletterUser.find(params[:id])
  end

  def create
    @newsletter_user = NewsletterUser.new(params[:newsletter_user])

      if @newsletter_user.save
        redirect_to newsletter_users_url, notice: 'News został dodany'
      else
        render action: "new"
      end
  end

  def update
    @newsletter_user = NewsletterUser.find(params[:id])

      if @newsletter_user.update_attributes(params[:newsletter_user])
        redirect_to newsletter_users_url, notice: "News został wyedytowany"
      else
        render action: "edit"
      end
  end

  def destroy
    @newsletter_user = NewsletterUser.find(params[:id])
    @newsletter_user.destroy

    redirect_to newsletter_users_url
  end
end

app/views/newsletter_users/_form.html.erb
<%= form_for(@newsletter_user, :html => {:multipart => true}) do |f| %>
  <% if @newsletter_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter_user.errors.count, "error") %> prohibited this newsletter_user from being saved:</h2>

      <ul>
      <% @newsletter_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :email, "Adres e-mail" %>
    <%= f.text_field :email %>
  </div>
  
  <div class="actions">
    <%= f.submit "Zapisz" %>
  </div>
<% end %>

app/views/newsletter_users/edit.html.erb
<h1>Edytuj News'a</h1>

<%= render 'form' %>

<%= link_to 'Powrót', newsletter_users_path %>

app/views/newsletter_users/index.html.erb
<div>
  <h1>Użytkownicy zapisani do newslettera</h1>
  <%= link_to "Dodaj", new_newsletter_user_path %>
  <br/>
  <br/>
  <br/>
  
  <table width="100%">
    <tr>
      <th width="60%">Adres e-mail</th>
      <th width="20%">Data zapisu</th>
      <th width="20%">Akcje</th>
    </tr>
    
    <% @newsletter_users.each do |nu| %>
      <tr>
	<td><%= nu.email %></td>
	<td><%= nu.created_at.strftime("%d-%m-%Y %H:%M:%S") %></td>
	<td><%= link_to 'Edytuj', edit_newsletter_user_path(nu) %> | <%= link_to 'Usuń', nu, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/newsletter_users/new.html.erb
<h1>Dodaj nowy wpis</h1>

<%= render 'form' %>

<%= link_to 'Powrót', newsletter_users_path %>

app/views/newsletter_users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>