config/routes.rb
MprojDev1::Application.routes.draw do

  match "szukaj" => "home#search", :as => :search

  match "wiadomosci" => "front_infos#index", :as => :front_infos
  match "wiadomosc/:id" => "front_infos#show", :as => :front_info
  
  match "wydarzenia" => "front_events#index", :as => :front_events
  match "wydarzenie/:id" => "front_events#show", :as => :front_event
  
  match "o-projekcie" => "home#about", :as => :front_about

  match "video" => "front_videos#index", :as => :front_videos
  match "video/:id" => "front_videos#show", :as => :front_video

  match "galerie" => "front_galleries#index", :as => :front_galleries
  match "galeria/:id" => "front_galleries#show", :as => :front_gallery
  match "galeria-zwieksz-priorytet/:id" => "galleries#prior_up", :as => :pages_prior_up
  match "galeria-zmniejsz-priorytet/:id" => "galleries#prior_down", :as => :pages_prior_down

  match "kontakt" => "home#contact", :as => :contact

  match "english" => "home#english", :as => :english

  match "strony" => "front_pages#index", :as => :front_pages
  match "strona/:id" => "front_pages#show", :as => :front_page

  match "zapisz-do-neewslettera" => "home#subscribe", :as => :subscribe
  match "wyslij-wiadomosc" => "home#send_message", :as => :send_mesage

  resources :infos
  resources :events
  resources :galleries
  resources :vids
  resources :pages
  resources :newsletter_users

  match "admin" => "admin#index", :as => :admin
  match "admin/login" => "admin#login", :as => :admin_login
  match "admin/enter" => "admin#enter", :as => :admin_enter
  match "admin/logout" => "admin#logout", :as => :admin_logout

  root :to => 'home#index'

end

app/models/info.rb
class Info < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/infos_controller.rb
# -*- encoding: utf-8 -*-
class InfosController < AdminController

  def index
    @infos = Info.all
  end

  def show
    @info = Info.find(params[:id])
  end

  def new
    @info = Info.new
  end

  def edit
    @info = Info.find(params[:id])
  end

  def create
    @info = Info.new(params[:info])

      if @info.save
        redirect_to infos_url, notice: 'News został dodany'
      else
        render action: "new"
      end
  end

  def update
    @info = Info.find(params[:id])

      if @info.update_attributes(params[:info])
        redirect_to infos_url, notice: "News został wyedytowany"
      else
        render action: "edit"
      end
  end

  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    redirect_to infos_url
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info, :html => {:multipart => true}) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title, "Tytuł" %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content, "Treść" %>
    <%= f.text_area :content, :class => 'mceEditor' %>
  </div>
  
  <div class="actions">
    <%= f.submit "Zapisz" %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Edytuj News'a</h1>

<%= render 'form' %>

<%= link_to 'Powrót', infos_path %>

app/views/infos/index.html.erb
<div>
  <h1>Wiadomości</h1>
  <%= link_to "Dodaj", new_info_path %>
  <br/>
  <br/>
  <br/>
  
  <table width="100%">
    <tr>
      <th width="60%">Tytuł</th>
      <th width="20%">Data publikacji</th>
      <th width="20%">Akcje</th>
    </tr>
    
    <% @infos.each do |info| %>
      <tr>
	<td><%= info.title %></td>
	<td><%= info.created_at.strftime("%d-%m-%Y %H:%M:%S") %></td>
	<td><%= link_to 'Edytuj', edit_info_path(info) %> | <%= link_to 'Usuń', info, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/infos/new.html.erb
<h1>Dodaj nowy wpis</h1>

<%= render 'form' %>

<%= link_to 'Powrót', infos_path %>